project:
  type: website
  output-dir: ../docs/
website:
  title: rpt
  code-links: true
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/UCD-SERG/rpt
        aria-label: rpt GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.md
      - section: Articles
        contents:
          - vignettes/getting-started.Rmd
          - vignettes/quarto_vignette.qmd
      - section: Reference
        contents:
          - text: example_function
            file: man/example_function.qmd
      - text: News
        file: NEWS.md
      - text: License
        file: LICENSE.md
      - text: Code of conduct
        file: CODE_OF_CONDUCT.md
      - text: Citation
        file: CITATION.md
format:
  html:
    code-link: true
